name: install-meltingpot

inputs:
  python-version:
    description: Python version
    required: false
    default: '3.10'
    type: string

runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Python dependencies
      shell: bash
      run: |
        pip install --upgrade pip
        pip install --editable .[dev]
