# Continuous integration tests.

name: pylint

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pylint.yml'
      - '.pylintrc'
      - 'examples/**'
      - 'meltingpot/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/pylint.yml'
      - '.pylintrc'
      - 'examples/**'
      - 'meltingpot/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  pylint:
    name: Lint Melting Pot
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Melting Pot
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - name: Set up Python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install pylint
      - name: Run PyLint
        run: pylint --disable=C,W,R --recursive=y meltingpot examples
