# Continuous integration tests.

name: pypi-test

on:
  schedule:
    - cron: "0 2 * * 1"  # Every Monday at 2am.
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pypi-status.yml'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/pypi-status.yml'
  workflow_dispatch:

permissions: read-all

jobs:
  run-meltingpot-tests:
    name: Test PyPI Distribution
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-11
          - macos-12
          - ubuntu-20.04
          - ubuntu-22.04
        python-version:
          - '3.10'

    steps:
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install pytest-xdist setuptools

      - name: Install from PyPI
        run: |
          pip -vvv install dm-meltingpot
          pip list

      - name: Test installation
        run: pytest --pyargs meltingpot
