name: pytype-examples

on:
  push:
    branches:
      - main
    paths:
      - '.github/actions/install-examples/action.yml'
      - '.github/actions/install-meltingpot/action.yml'
      - '.github/workflows/pytype-examples.yml'
      - 'examples/**'
      - 'meltingpot/**'
      - 'pyproject.toml'
      - 'setup.py'
  pull_request:
    branches:
      - main
    paths:
      - '.github/actions/install-examples/action.yml'
      - '.github/actions/install-meltingpot/action.yml'
      - '.github/workflows/pytype-examples.yml'
      - 'examples/**'
      - 'meltingpot/**'
      - 'pyproject.toml'
      - 'setup.py'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  pytype:
    name: Typecheck examples
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Melting Pot
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Install examples
        uses: ./.github/actions/install-examples

      - name: Run PyType on examples
        run: pytype examples
