# Continuous integration tests.

name: pytype

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pytype.yml'
      - 'examples/**'
      - 'meltingpot/**'
      - 'pyproject.toml'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/pytype.yml'
      - 'examples/**'
      - 'meltingpot/**'
      - 'pyproject.toml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  pytype:
    name: Typecheck Melting Pot
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: ${{ github.event_name != 'workflow_dispatch' }}
    steps:
      - name: Checkout Melting Pot
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - name: Set up Python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install setuptools pytype
      - name: Install Melting Pot
        run: pip -vvv install .
      - name: Run PyType on Melting Pot
        run: pytype meltingpot
      - name: Install example requirements
        run: pip -vvv install -r examples/requirements.txt
      - name: Run PyType on examples
        run: pytype examples
