name: pytype-meltingpot

on:
  push:
    branches:
      - main
    paths:
      - '.github/actions/install-meltingpot/action.yml'
      - '.github/workflows/pytype-meltingpot.yml'
      - 'examples/**'
      - 'meltingpot/**'
      - 'pyproject.toml'
  pull_request:
    branches:
      - main
    paths:
      - '.github/actions/install-meltingpot/action.yml'
      - '.github/workflows/pytype-meltingpot.yml'
      - 'examples/**'
      - 'meltingpot/**'
      - 'pyproject.toml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  pytype:
    name: Typecheck Melting Pot
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Melting Pot
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Install Melting Pot
        uses: ./.github/actions/install-meltingpot

      - name: Run PyType on Melting Pot
        run: pytype meltingpot
