# Continuous integration tests.

name: test-meltingpot

on:
  push:
    paths:
      - '.github/workflows/test-meltingpot.yml'
      - 'meltingpot/**'
      - 'setup.py'
  pull_request:
    paths:
      - '.github/workflows/test-meltingpot.yml'
      - 'meltingpot/**'
      - 'setup.py'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  test-meltingpot:
    name: Test Melting Pot
    runs-on: ${{ matrix.os }}
    env:
      SYSTEM_VERSION_COMPAT: 0  # See https://github.com/actions/setup-python/issues/279.
    timeout-minutes: 90
    strategy:
      fail-fast: ${{ github.event_name != 'workflow_dispatch' }}
      matrix:
        os:
          - macos-11
          - ubuntu-20.04
        python-version:
          - '3.10'
    steps:
      - name: Set up Python
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install setuptools pytest-xdist
      - name: Install Melting Pot
        run: |
          pip -vvv install https://github.com/deepmind/meltingpot/archive/${{ github.sha }}.tar.gz
          pip list
      - name: Test Melting Pot
        run: pytest --pyargs meltingpot
