name: test-meltingpot

on:
  push:
    branches:
      - main
    paths:
      - '.github/actions/install-meltingpot/action.yml'
      - '.github/workflows/test-meltingpot.yml'
      - 'meltingpot/**'
      - 'setup.py'
      - 'pyproject.toml'
  pull_request:
    branches:
      - main
    paths:
      - '.github/actions/install-meltingpot/action.yml'
      - '.github/workflows/test-meltingpot.yml'
      - 'meltingpot/**'
      - 'setup.py'
      - 'pyproject.toml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  pytest:
    name: Test Melting Pot
    runs-on: ${{ matrix.os }}
    env:
      SYSTEM_VERSION_COMPAT: 0  # See https://github.com/actions/setup-python/issues/279.
    timeout-minutes: 120
    strategy:
      fail-fast: ${{ github.event_name != 'workflow_dispatch' }}
      matrix:
        os:
          - macos-11
          - ubuntu-20.04
        python-version:
          - '3.10'
    steps:
      - name: Checkout Melting Pot
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Install Melting Pot
        uses: ./.github/actions/install-meltingpot
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test Melting Pot
        run: pytest meltingpot
