# Continuous integration tests.

name: test-examples

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test-examples.yml'
      - 'examples/**'
      - 'meltingpot/**'
      - 'setup.py'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/test-examples.yml'
      - 'examples/**'
      - 'meltingpot/**'
      - 'setup.py'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  test-examples:
    name: Test examples
    runs-on: ubuntu-latest
    env:
      SYSTEM_VERSION_COMPAT: 0  # See https://github.com/actions/setup-python/issues/279.
    timeout-minutes: 90
    steps:
      - name: Checkout Melting Pot
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - name: Set up Python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install setuptools pytest-xdist
      - name: Install Melting Pot
        run: |
          pip -vvv install .
          pip list
      - name: Install examples
        run: |
          pip install -r examples/requirements.txt
          pip list
      - name: Test examples
        run: pytest examples
